### ISSUE TITLE
your caffe compile error

### ISSUE THREAD

**Issue by kingvision** [AlfredXiangWu/face_verification_experiment#10]
hi,
  when i compile your caffer, i got an error;

[100%] Built target test.testbin
Scanning dependencies of target runtest
Cuda number of devices: 1
Current device id: 0
Note: Randomizing tests' orders with a seed of 18076 .
[==========] Running 836 tests from 167 test cases.
[----------] Global test environment set-up.
[----------] 10 tests from DataLayerTest/3, where TypeParam = caffe::DoubleGPU
[ RUN      ] DataLayerTest/3.TestReadLevelDB
[       OK ] DataLayerTest/3.TestReadLevelDB (1748 ms)
[ RUN      ] DataLayerTest/3.TestReadCropTestLevelDB
[       OK ] DataLayerTest/3.TestReadCropTestLevelDB (323 ms)
[ RUN      ] DataLayerTest/3.TestReadCropTrainLevelDB
[       OK ] DataLayerTest/3.TestReadCropTrainLevelDB (311 ms)
[ RUN      ] DataLayerTest/3.TestReadCropTrainSequenceUnseededLevelDB
[       OK ] DataLayerTest/3.TestReadCropTrainSequenceUnseededLevelDB (411 ms)
[ RUN      ] DataLayerTest/3.TestReadCropTrainSequenceSeededLevelDB
[       OK ] DataLayerTest/3.TestReadCropTrainSequenceSeededLevelDB (455 ms)
[ RUN      ] DataLayerTest/3.TestReadLMDB
[       OK ] DataLayerTest/3.TestReadLMDB (67 ms)
[ RUN      ] DataLayerTest/3.TestReadCropTrainLMDB
[       OK ] DataLayerTest/3.TestReadCropTrainLMDB (44 ms)
[ RUN      ] DataLayerTest/3.TestReadCropTrainSequenceUnseededLMDB
[       OK ] DataLayerTest/3.TestReadCropTrainSequenceUnseededLMDB (51 ms)
[ RUN      ] DataLayerTest/3.TestReadCropTrainSequenceSeededLMDB
[       OK ] DataLayerTest/3.TestReadCropTrainSequenceSeededLMDB (50 ms)
[ RUN      ] DataLayerTest/3.TestReadCropTestLMDB
[       OK ] DataLayerTest/3.TestReadCropTestLMDB (50 ms)
[----------] 10 tests from DataLayerTest/3 (3510 ms total)

[----------] 2 tests from HingeLossLayerTest/3, where TypeParam = caffe::DoubleGPU
[ RUN      ] HingeLossLayerTest/3.TestGradientL1
[       OK ] HingeLossLayerTest/3.TestGradientL1 (7 ms)
[ RUN      ] HingeLossLayerTest/3.TestGradientL2
[       OK ] HingeLossLayerTest/3.TestGradientL2 (4 ms)
[----------] 2 tests from HingeLossLayerTest/3 (11 ms total)

[----------] 5 tests from BenchmarkTest/1, where TypeParam = caffe::DoubleCPU
[ RUN      ] BenchmarkTest/1.TestTimerStop
[       OK ] BenchmarkTest/1.TestTimerStop (0 ms)
[ RUN      ] BenchmarkTest/1.TestTimerStart
[       OK ] BenchmarkTest/1.TestTimerStart (0 ms)
[ RUN      ] BenchmarkTest/1.TestTimerConstructor
[       OK ] BenchmarkTest/1.TestTimerConstructor (0 ms)
[ RUN      ] BenchmarkTest/1.TestTimerSeconds
[       OK ] BenchmarkTest/1.TestTimerSeconds (300 ms)
[ RUN      ] BenchmarkTest/1.TestTimerMilliSeconds
[       OK ] BenchmarkTest/1.TestTimerMilliSeconds (300 ms)
[----------] 5 tests from BenchmarkTest/1 (600 ms total)

[----------] 3 tests from ThresholdLayerTest/2, where TypeParam = caffe::FloatGPU
[ RUN      ] ThresholdLayerTest/2.Test
F1009 13:28:41.059129 11432 threshold_layer.cu:26] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
**\* Check failure stack trace: ***
    @     0x2b5e7d906daa  (unknown)
    @     0x2b5e7d906ce4  (unknown)
    @     0x2b5e7d9066e6  (unknown)
    @     0x2b5e7d909687  (unknown)
    @           0xad8909  caffe::ThresholdLayer<>::Forward_gpu()
    @           0x7b3acf  caffe::Layer<>::Forward()
    @           0x861c79  caffe::ThresholdLayerTest_Test_Test<>::TestBody()
    @           0x9f84ad  testing::internal::HandleSehExceptionsInMethodIfSupported<>()
    @           0x9f38f6  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x9e0ccb  testing::Test::Run()
    @           0x9e1464  testing::TestInfo::Run()
    @           0x9e1a52  testing::TestCase::Run()
    @           0x9e68dc  testing::internal::UnitTestImpl::RunAllTests()
    @           0x9f9842  testing::internal::HandleSehExceptionsInMethodIfSupported<>()
    @           0x9f4635  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x9e5670  testing::UnitTest::Run()
    @           0x9d97b6  main
    @     0x2b5e7fb78ec5  (unknown)
    @           0x7a7859  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
make[3]: **\* [src/caffe/test/CMakeFiles/runtest] Error 134
make[2]: **\* [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
make[1]: **\* [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
make: **\* [runtest] Error 2
li@li:~/code/caffe/face/caffe-hybrid_dev/build$ 

how i can fix it?
thanks

**Comment by AlfredXiangWu** [comment]
The step "make test" and "make runtest" are not necessary for using caffe. It can only check whether the gradient is realized correctly or not. 
In my caffe project, I have written some layers but don't write their test layers. If "make" is successfully, the project could be used for training and testing. 
And you can use caffe release candidate version which is released on 19 Sep 2014 to train my model.
