### ISSUE TITLE
LightenedCNN_B - Unknown bottom blob 'label'

### ISSUE THREAD

**Issue by matbloch** [AlfredXiangWu/face_verification_experiment#100]
When I'm loading the B model I get the following error:

`F0117 09:32:11.588213    22 insert_splits.cpp:29] Unknown bottom blob 'label' (layer 'accuracy', bottom index 1)`

I also noticed that there might be an inconsistency in the prototxt file.
E.g. in the layer **etlwise_fc1** is misspelled. Sometimes its called "**etl**wise_fc1" and at other locations "**elt**wise_fc1".

**Comment by AlfredXiangWu** [comment]
You can remove the "Accuracy" layer in deploy.prototxt.
