### ISSUE TITLE
Classification using model trained on own dataset

### ISSUE THREAD

**Issue by psakamoori** [AlfredXiangWu/face_verification_experiment#103]
Hi,

I am following below steps to train my own data set, generate model and to classify similar faces 
1. Extract Face images (of each person), align them to 144 x 144 size
2. Train the faces using model C prototxt
3. For Classification, I extract face image of test data, align them to 128 x 128 and use generated .caffemodel to classify.

I am trying use this for face recognition

Is this the right steps? Is this the right way to train my own data set and generate model file.
or Should I fine tune using the existing LFW trained model? Appreciate your reply

**Comment by AlfredXiangWu** [comment]
I think it's right.
