### ISSUE TITLE
Some questions regarding LFW benchmark report

### ISSUE THREAD

**Issue by ntvy95** [AlfredXiangWu/face_verification_experiment#104]
Hello, I'm new to these technologies so pardon me if I say anything ridiculous.

According to [LFW's new update](http://vis-www.cs.umass.edu/lfw/lfw_update.pdf), it looks like in unsupervised protocol they adopt AUC as a measure of accuracy rather than EER and they do not allow the label or identity information to be introduced in the training phase in any way. So it looks like you are not following LFW's official unsupervised setting? Can you please provide me the link / paper to the benchmark  that you are following? I'm curious about this benchmark and would like to learn more.

Aside from that, I also have a question regarding the VGG performance in Table 3. Did you use the [configuration A model provided by VGG](http://www.robots.ox.ac.uk/~vgg/software/vgg_face/) or you yourself additionally train VGG's configuration B network based on their provided configuration A model? If it is the latter case, can you please publish your trained configuration B model? If you can't, can you please tell me the information of the two convolution layers that you added to turn configuration A into configuration B?

Thank you very much!

**Comment by AlfredXiangWu** [comment]
1. The "unsupervised" in the paper means the model is not trained on LFW followed the 10-fold evaluation. We train the CNN on MS-Celeb-1M and extract features of LFW. And then we directly compute cosine similarities of 6000 pairs. 

2. We only use the official released VGG model.

**Comment by ntvy95** [comment]
Thank you very much for your reply! I have found that MS-Celeb-1M and LFW share some mutual identities, such as Charlotte Rampling. So did you exclude identities in LFW from MS-Celeb-1M before the training or not?

**Comment by AlfredXiangWu** [comment]
I don't remove the inclusive identities of LFW in MS-Celeb-1M.

**Comment by ntvy95** [comment]
Thank you very much for your reply!
