### ISSUE TITLE
How to calculate similarity in percentage?

### ISSUE THREAD

**Issue by zhangguanqun** [AlfredXiangWu/face_verification_experiment#107]
The cosine distance of two faces is ranged from -1 to 1, how to change or project this value to a percentage representation which ranged from 0% to 100%?
Thanks!

**Comment by AlfredXiangWu** [comment]
There are lots of linear or nonlinear transformations which can project scores from [-1, 1] to [0, 1]. 
For example, a simple way is (similarity + 1)/2.

**Comment by zhangguanqun** [comment]
It looks like too simple, isn't it?
Could you give me some recommendations? 
Thanks a lot.
