### ISSUE TITLE
Where can i find the mean files?

### ISSUE THREAD

**Issue by aisacode** [AlfredXiangWu/face_verification_experiment#108]

**Comment by zhangguanqun** [comment]
No need to minus the mean.

**Comment by aisacode** [comment]
Thank you for the answer!

If I run the network with random images without any normalization of the network it seems to fall into the same  3-4 classes. The problem is alleviated if the images are scaled (by factor of 256). 
What is the correct procedure for feed the network and extract a consistent feature set (considering to catch the output of the layer "etlwise_fc1")?
