### ISSUE TITLE
train_data for model C

### ISSUE THREAD

**Issue by lyuchuny3** [AlfredXiangWu/face_verification_experiment#112]
Hi, I have a question for the train data you use for model C. 
I see the number of class for MS_Celeb_1M_clean_list is 79077, for the whole MS_Celeb_1M dataset is 99891. I see your proto for model C, the number  of output is 99891. 

Do you use the whole MS dataset or use the MS_clean_list  to train model C?

**Comment by AlfredXiangWu** [comment]
The released model is trained on clean dataset. 
When training this model, I don't re-label the clean dataset, therefore, the number of output for fc2 is 99891.
