### ISSUE TITLE
MegaFace evalutation: How to save a OpenCV mat (bin) by using matio.py?

### ISSUE THREAD

**Issue by globallocal** [AlfredXiangWu/face_verification_experiment#113]
Hello, Mr Wu:
        I have study how to evaluate a model on MegaFace recently. But I confuse how to convert a vector into bin form. The default material said matio.py is a good tool. But I don't understand it without the comment. Could you tell me something about it ? Thank you so much.

**Comment by AlfredXiangWu** [comment]
I don't use matio.py to generate feature. 

There are some tips about generating features for megaface:
- Each face image corresponds to a feature file (bin). The format of each bin's name is "imgName_xxxxxx.bin", for example, 6680193223_0.jpg_lightenedcnn_256.bin.
- The format of binary feature file is "4 * int + feature_len * float". The "4*int" numbers are your lengths of features, 1, 4 and 5. 
- The official code is based on L2 distance, If you use cosine similarity, the features should be normalized to 1.

There is a [demo code](https://gist.github.com/AlfredXiangWu/2a9c0a7ea92111baf44d6b099eb73dbc) to generating features by caffe. You can refer to it for your own.

**Comment by globallocal** [comment]
Thank you so much, I'll try later.

**Comment by globallocal** [comment]
Hi, Mr Wu.  Is the extract_features.cpp a windows version? When I compile it on Linux  platform, some errors emerge. For example:
tools/extract_features_github.cpp:191:9: error: no matching function for call to ‘caffe::Net<float>::Forward()’feature_extraction_net.Forward();

**Comment by AlfredXiangWu** [comment]
The code can be compiled on Linux. It is based on my own caffe version, therefore, I only provide it for you as a reference to implement your own code for megaface feature generation.

**Comment by globallocal** [comment]
Than you for replying.  Actually, I can understand the meaning of the code, maybe the version of caffe is not the same. I will try to modify it for my own usage. Thank you again. See you.

**Comment by tangxman** [comment]
Hi, Mr Wu, I hava got the cmc_facescrub_megaface_{algorithm name}_{distractor set size}_{set #}.json and matches_facescrub_megaface_{algorithm name}_{distractor set size}_{set #}.json, how can I get the results reported in http://megaface.cs.washington.edu/results/facescrubresults.html?

**Comment by AlfredXiangWu** [comment]
@tangxman I think you can upload the features and results on the provided google drive and send emails to MegaFace Team.

**Comment by tangxman** [comment]
@AlfredXiangWu thanks, I already did. I have another question, I have downloaded the json results(http://megaface.cs.washington.edu/Challenge1JSON.zip) reported on the leaderboard, how can I draw the identification rate curve like this((http://megaface.cs.washington.edu/results/content/challengeresults/facescrub_rank-1_cmbnd_set_1.jpg))? I can't understand the meaning of the cms and matches json file .

**Comment by AlfredXiangWu** [comment]
@tangxman 

```
"cmc" : 
	[
		[ 0, 1, 2, 3, 5, 9, 17, 34, 77, 202, 677, 4085, 89220, 1000000 ],
		
		[
			0.7479854822158813,
			0.8509835004806519,
			0.8807100057601929,
			0.8953226208686829,
			0.9081453084945679,
			0.9192366003990173,
			0.9297746419906616,
			0.9399676918983459,
			0.9499850273132324,
			0.9600023627281189,
			0.9700196385383606,
			0.9800239801406860,
			0.9900282621383667,
			1.0
		]
	]
```

For example, you can define
```
x = [ 0, 1, 2, 3, 5, 9, 17, 34, 77, 202, 677, 4085, 89220, 1000000 ] 
y = [
			0.7479854822158813,
			0.8509835004806519,
			0.8807100057601929,
			0.8953226208686829,
			0.9081453084945679,
			0.9192366003990173,
			0.9297746419906616,
			0.9399676918983459,
			0.9499850273132324,
			0.9600023627281189,
			0.9700196385383606,
			0.9800239801406860,
			0.9900282621383667,
			1.0
		]
```
Then you can use matlab function plot to draw the cmc curve. 
`plot(x, y)`

The curve is the similar to the one of "identification rate vs rank". More details about cmc curves and the relationship between roc and cmc are shown in the[ slides](https://www.nist.gov/sites/default/files/documents/2016/12/06/12_ross_cmc-roc_ibpc2016.pdf). 

About the curves you mentioned, it is "identification rate vs distractors", the x axis is only changed from rank-n to the number of distractors in gallery.

**Comment by ZHAIXINGZHAIYUE** [comment]
大神您好，我下载下来的megaface 数据集解压之后，含有　1028040 个json文件,　含有1028062张图片，它们的数量并不相同，您的也是这样吗？谢谢
　没有对应json文件的图片;
megaface/FlickrFinal2/380/38097660@N04/5140422204_0.jpg
megaface/FlickrFinal2/380/38097660@N04/5140422204_16.jpg
megaface/FlickrFinal2/380/38097660@N04/5140422204_13.jpg
megaface/FlickrFinal2/380/38097660@N04/5140422204_3.jpg
megaface/FlickrFinal2/380/38097660@N04/5140422204_14.jpg
megaface/FlickrFinal2/380/38097660@N04/5140422204_9.jpg
megaface/FlickrFinal2/380/38097660@N04/5140422204_5.jpg
megaface/FlickrFinal2/027/027A25Gf.JPG
megaface/FlickrFinal2/042/042A04.JPG
megaface/FlickrFinal2/009/009A13Gf.JPG
megaface/FlickrFinal2/063/063A08.JPG
megaface/FlickrFinal2/077/077A02Gf.JPG
megaface/FlickrFinal2/033/033A02.JPG
megaface/FlickrFinal2/014/014A03Gf.JPG
megaface/FlickrFinal2/585/58537888@N05/7683597692_0.jpg
megaface/FlickrFinal2/024/024A05.JPG
megaface/FlickrFinal2/045/045A03.JPG
megaface/FlickrFinal2/060/060A20Gf.JPG
megaface/FlickrFinal2/025/025A03Gf.JPG
megaface/FlickrFinal2/044/044A01.JPG
megaface/FlickrFinal2/082/082A22.JPG

**Comment by ZHAIXINGZHAIYUE** [comment]
@AlfredXiangWu @tangxman @globallocal 
There are some images in megaface dataset that dosen't contain any faces. 
How to treat these imgs during extracting face feature?
Thank you.

**Comment by globallocal** [comment]
@ZHAIXINGZHAIYUE  I think these images contribute to the negative face pairs. And we only need to treat them as special face images and just crop the detected areas for comparison. Are you agree with me ?

**Comment by globallocal** [comment]
@AlfredXiangWu @tangxman 
        When I run my own features for MegaFace Challenge 1, I have got the problem "Could not load probe scores!" .  Should I create the bin file like "/devkit/models/jb_LBP.bin" ? Do you known what "jb_LBP.bin" saves ?

**Comment by globallocal** [comment]
@AlfredXiangWu @tangxman I have found the reason why  "Could not load probe scores!" happens,  I finally use the python code to save the extracted feature to avoid the problem.  However, I still suspect that  "Default: ../models/jb_identity.bin'  leads to a series of problems.
 
Do you use "Default: ../models/jb_identity.bin' for your own features? If not, how to create a identity.bin for your own features? Looking forward for reply. Thank you.

**Comment by fuying-wang** [comment]
@AlfredXiangWu  Hi，Mr Wu, I have two questions about megaface challenge to ask you.I have run the first challenge and I can't understand the json file.  How can I use the file matches_facescrub_megaface_{algorithm name}{distractor set size}{set #}.json to draw the ROC curve like http://megaface.cs.washington.edu/results/content/challengeresults/fgnet_1000000_distractors_cmbnd_verif_set_1.jpg ?

**Comment by fuying-wang** [comment]
@AlfredXiangWu Sorry to bother you. And I have another question. The first element in x is 0, however, the first element of y  is indeed the rank 1 identification rate . I can't understand why it is 0?
