### ISSUE TITLE
发现model_B和model_C网络 prototxt文件基本是一样的?

### ISSUE THREAD

**Issue by lei-xiong** [AlfredXiangWu/face_verification_experiment#115]
Hi @AlfredXiangWu
     对比看了你提供的model_B和model_C网络，两个网络deploy prototxt文件基本是一样的。能否提供model_C网络的训练文件。谢谢

**Comment by AlfredXiangWu** [comment]
> The model A and B is trained on **CASIA-WebFace** by **caffe-rc**.
> The model C is trained on **MS-Celeb-1M** by **caffe-rc3**.

**Comment by xionglei181818** [comment]
model_B和model_C这两个网络本身是一样的，只是数据集不一样？在论文上看到的前后两篇论文《A Light CNN for Deep Face Representation》 和《A Light CNN for Deep Face Representation with Noisy Labels》网络结构和卷积核等参数还是不一样的，这个是我理解错了吗？谢谢
