### ISSUE TITLE
关于ffp的一些问题

### ISSUE THREAD

**Issue by leeeeeeo** [AlfredXiangWu/face_verification_experiment#117]
您好。
您给出[http://mmlab.ie.cuhk.edu.hk/archive/CNN_FacePoint.htm](url)来生成.5pt文件。
但是CASIA数据集好像没有给出boundingbox。那怎么得到bbox.txt这个文件呢？

另外，生成的文件是result.bin，怎么把它转换成.5pt文件呢？
谢谢！
：）

**Comment by AlfredXiangWu** [comment]
Refer to PR https://github.com/AlfredXiangWu/face_verification_experiment/pull/61/commits/ffcabda8aea8f24df92784a6baeea719559f54ca or issue https://github.com/AlfredXiangWu/face_verification_experiment/issues/15
