### ISSUE TITLE
MS-Celeb-1M clean list name

### ISSUE THREAD

**Issue by ustcluq** [AlfredXiangWu/face_verification_experiment#119]
Hi, can you tell me the meaning of list, such as  "m.0109kg/14-FaceId-0.jpg 0".  Is the last '0'  the lable of this image?  
哈哈，英语蹩脚，我命名看到有的最后的那个类标签一样，可不是同一个人呀，比如胡锦涛的那些照片。。

**Comment by AlfredXiangWu** [comment]
The clean list is generated by a model automatically, therefore, I cannot ensure that there are not noisy labeled images in each identity.

**Comment by BIG-CHENG** [comment]
There are definitely noisy labelled images, just check any directory would know that.

**Comment by anguoyang** [comment]
I have the same question, can anyone tell me how to get rid of these dirty images?
