### ISSUE TITLE
matlab evaluate error

### ISSUE THREAD

**Issue by kingvision** [AlfredXiangWu/face_verification_experiment#12]
hi ,
   i run the matlab evaluation.m code . i got the error:
   未定义与 'single' 类型的输入参数相对应的函数 'vl_pr'。
  is there no "vl_pr" function?
thanks

**Comment by AlfredXiangWu** [comment]
You can download vlfeat toolbox (https://github.com/AlfredXiangWu/matlab_misc/tree/master/face_verification/evaluation/vlfeat-master)

**Comment by sunshineInmoon** [comment]
hi,
i run the matlab evaluation.m code. i got the errro:
尝试引用非结构体数组的字段。

出错 evaluation.accuracy.eval (line 8)
    class = 2 \* (scores >= config.threshold) - 1;
i don't find the struct named config. i think the config is 'ap','roc' or 'accuracy', but i can't find ap.threshold.whert is it?
thanks!
