### ISSUE TITLE
shuffle train imgs for model C?

### ISSUE THREAD

**Issue by lyuchuny3** [AlfredXiangWu/face_verification_experiment#120]
Hi,
I have a questions about the order of training data.
Do you shuffle the train data when generating the train_lmdb for model C?

In face, directly shuffle in the step of generate lmdb for big database has memory problem. An other approach is the generate a shuffle label list. Then generate lmdb with the shuffled list.

**Comment by AlfredXiangWu** [comment]
I generate the lmdb with a shuffled list
