### ISSUE TITLE
LightenedCNN_B_lfw.mat 里的features是如何得到的？

### ISSUE THREAD

**Issue by leeeeeeo** [AlfredXiangWu/face_verification_experiment#121]
您好！
我在测试准确率的过程中看到您将图片提取的特征放在了LightenedCNN_B_lfw.mat里的features里。
运行后准确率达到了99%
但是我用自己提取的特征再运行，准确率很低（使用您提供的caffemodel提取特征）。
我觉得是不是我提取特征这一步的代码没有写好。
所以您是否方便提供一下 提取特征 的代码？
谢谢！

**Comment by AlfredXiangWu** [comment]
可以参考这份python代码：
https://github.com/AlfredXiangWu/python_misc/blob/master/caffe/caffe_ftr.py
但是需要注意当前版本的caffe python接口已经不支持此代码

**Comment by leeeeeeo** [comment]
谢谢您的回答！
我去试试这个python代码。
当然，如果您能提供您当时提取features的代码就更好啦~

**Comment by ghost** [comment]
@leeeeeeo 我也遇到了这个问题，不过我用的A模型，提取的“eltwise6”这一层。请问您解决了吗？

**Comment by leeeeeeo** [comment]
@eg3355 提取特征的话，参考一下这个https://github.com/Tonyfy/LCNN_TRAIN/tree/master/demo里面的demo.py吧。

**Comment by ghost** [comment]
🙏，谢谢！




发自网易邮箱大师
在2017年06月15日 13:31，leeeeeeo 写道：

@eg3355 提取特征的话，参考一下这个https://github.com/Tonyfy/LCNN_TRAIN/tree/master/demo里面的demo.py吧。
