### ISSUE TITLE
有关 LightenedCNN_B_lfw.mat 里的labels的问题请教

### ISSUE THREAD

**Issue by leeeeeeo** [AlfredXiangWu/face_verification_experiment#122]
您好.
我也像LightenedCNN_B_lfw.mat 里的labels一样生成了自己的labels.
labels是每一个人所属的类别.
但是我们的labels并不一样.
举个例子,第50个人的label,您认为是17.但是事实上第50个人的label是18.
还有很多这样的情况.
您可否解释一下这样做是什么道理?
谢谢!

**Comment by AlfredXiangWu** [comment]
当时label生成有些错误，但是evaluation时并不需要label，对结果无影响

**Comment by leeeeeeo** [comment]
谢谢您的回答！
