### ISSUE TITLE
solver of model_B

### ISSUE THREAD

**Issue by liangsirrun** [AlfredXiangWu/face_verification_experiment#123]
@AlfredXiangWu could you share your solver of model  b?

**Comment by AlfredXiangWu** [comment]
Refer to issue https://github.com/AlfredXiangWu/face_verification_experiment/issues/110

**Comment by ctgushiwei** [comment]
@AlfredXiangWu  you mean you train model B and model C with the same solver?

**Comment by AlfredXiangWu** [comment]
@ctgushiwei The difference between B and C is only the training dataset. You can modify the max_iter and stepsize according to the number of images in the training dataset.
