### ISSUE TITLE
feature Extract

### ISSUE THREAD

**Issue by zuoshaobo** [AlfredXiangWu/face_verification_experiment#124]
1.i extract the feature  by your trained model B,and test the lfw acc just 95%,i do not know the reason, but i use your LightenedCNN_B_lfw.mat to test ,it is 98.1%,  so is my operation error?,the feature size is 256
i extract layer "eltwise_fc1" ,the lfw dataset is aligned  i download
2.The train size is 128: i see you use crop_size:128,but i used new_height/new_with,like below:
image_data_param {
 source: "train.txt"  
 batch_size: 100
new_height:128
new_width:128
}
so ,what the size of you train image ?, what the  caffe train accurcy is? 
3. I see a csdn blog :blog.csdn.net/qq_14845119/article/details/56677339, do you know the lightcnn S Model?

thank u

**Comment by honghuCode** [comment]
@zuoshaobo please download  lightcnn S Model at http://download.csdn.net/download/honghu549599aaa/10141247
