### ISSUE TITLE
Will the CNN29 model released or not?

### ISSUE THREAD

**Issue by stupiding** [AlfredXiangWu/face_verification_experiment#134]
I have recently read the new paper of CNN29 MFM model, and know that the new precision has been 99.33%. Will it be released? If not, I should try to train the model myself with my poor computation resources T_T

**Comment by lixiaohui2020** [comment]
I want to know which paper you are reading. Can you send a link? Thank you!

**Comment by stupiding** [comment]
https://arxiv.org/pdf/1511.02683.pdf
