### ISSUE TITLE
Different ROC result between provided matlab code and PhD face recognition toolbox

### ISSUE THREAD

**Issue by a00achild1** [AlfredXiangWu/face_verification_experiment#136]
Hi, I recently found out the ROC curve generate from your matlab code is different from the PhD face recognition toolbox ([https://www.mathworks.com/matlabcentral/fileexchange/35106-the-phd-face-recognition-toolbox#functions_tab](url))
I use the same features as input, but got the different ROC results as below:
my features ----> [https://drive.google.com/file/d/0B4OSqkUVPXIsaXJmMGsyMnhyQ0U/view?usp=sharing](url)
(LFW features: 13233 256 dims. feature vectors)
![untitled](https://user-images.githubusercontent.com/20927157/28022316-663e84ac-65bd-11e7-84f5-a0e890e3dfd1.png)
Could someone help me verify the results? Or maybe this is my own fault?

**Comment by AlfredXiangWu** [comment]
The verification rate of phd face recognition toolbox is different from the ROC defined on [wiki](https://en.wikipedia.org/wiki/Receiver_operating_characteristic). 

As written in my evaluation code, the verification rate means true positive rate (TPR), which is defined as (1-FNR). But in phd face recognition toolbox, the verification rate is defined as (1-FRR). 

About the difference between FNR and FRR, you can refer to https://www.researchgate.net/post/False_positive_rate_false_rejection_rate_and_false_alarm_probability2

**Comment by a00achild1** [comment]
@AlfredXiangWu thanks for your explanation! I think I got mess around these definition
I'll check out the definition carefully later
