### ISSUE TITLE
eltwise_fc1 layer features not as expected

### ISSUE THREAD

**Issue by beppe2hd** [AlfredXiangWu/face_verification_experiment#137]
Hi,

We tried to extract features using the LightenedCNN_C_deploy model using the LFW normalized  images.
We tried to use both the fc1 and eltwise_fc1 features but they do not match the expected output.
1) The fc1 returns a vector of 512 elements 
2) The eltwise_fc1 returns a vector of correct size (256 elements) but showing features in a range of [-1000 1000] whereas the features provided in the matlab range in [-20 20].

We are working with caffe by means c++ language 

Can you help me?

**Comment by a00achild1** [comment]
@beppe2hd 
You need to transformed the input image to 32FC1 and scale all elements to [0, 1]
