### ISSUE TITLE
FINETUNING问题

### ISSUE THREAD

**Issue by westpilgrim** [AlfredXiangWu/face_verification_experiment#140]
你好，在复现你论文里 “ 先在CASIA数据集上训练直到收敛，然后去掉CASIA的FC2层，换上MSCELEB的FC2层，固定前面的层，训练直到网络大致收敛，然后放开前面的层，在MSCELEB数据集上进行FINETUNING ” 这个方法的时候，我换上了MSCELEB的FC2层，设置propagate_down : 0（为了固定前面的层的参数），但发现SOFTMAX LOSS从40多降到11多就再也不降了，哪怕迭代了70万次也是这样，无法收敛。作者有过这样的经历吗？原因是什么？@AlfredXiangWu

**Comment by AlfredXiangWu** [comment]
You can directly train Light CNN on ms-celeb-1m by the clean list.

**Comment by westpilgrim** [comment]
my gpu is poor , i can't wait to see the result of train ms from scratch.
