### ISSUE TITLE
why the input data demension is (20, 1, 128, 128)?

### ISSUE THREAD

**Issue by yiakwy** [AlfredXiangWu/face_verification_experiment#143]
Perhaps 20 represented 20 eigen faces?
suppose input grey image ( colour channels converted to grey using weighted sum) being of the size (r, c)

for n samples, we got 20 eigen faces (20, r, c), for newly coming image b (r, c), we do normal projects by  (1, r*c) * (r*c, 20), we can only get (1, 20).

So how did you get a model with input dimension starting from 20.

**Comment by medivhna** [comment]
Ignorance is not a shame, arrogance is.

**Comment by yiakwy** [comment]
This is your problem when you make it public. We need to clarify any potential problems which might confuse with users.

First of first, to use your model, considering a scenario, given an image of size 250*250, (LFW aligns images to 250 * 250), your need to feed it into net, where first layer is 
(28, 1,128, 128).

This confuses people. 

Can you explain it? It is shame your work incomplete and you published it.

**Comment by yiakwy** [comment]
@medivhna Prudence is not a shit, prejudice is

**Comment by medivhna** [comment]
@yiakwy If you're not satisfied with this project, you can close this page and choose other works. Your rude and arrogant attitude has no help to solve your problem.

You can refer all the details of implementation in the original paper. Why should the owner repeat again on GitHub? I haven't seen any foolish issue like this in any deep face recognition project ever before.

BTW, I have no personal relationship with the owner Wu, but LightCNN is an outstanding work for the community of deep face recognition. It's kind of him to open-source this project on GitHub. If you have any doubt and objection, give your arguments accurately and politely, not just "ridiculous".

The owner is not your babysitter.

**Comment by yiakwy** [comment]
@medivhna talking to you is wasting of my time when you are judging. 

Whether I am satisfied with project has NO BUSINESS WITH you. I am talking about questions.

**The issue will be kept until someone gives correct answers to it**. I will keep an eye on it. But that does not mean I need use his implemntation. You have no idea what is open source. I can implement my own NN from scratch, so for me this is not a problem. You should understand what I am talking about because my description is detailed enough for normal reading tasks. If you have difficulties to understand, you can tell me. I will give you answer as long as I am able to.

If you havn't see any "foolish" question like this before, now you do. You cannot even prove that you understand the silly the question after you saw it UNCOVERED BY ME. YOUR MOM SHOULD' VE TAUGHT YOU ABOUT APPRECIATION. Save your negative energy.  Is your answer related to the question? 

> """The only thing need NOW is a correct model to do classification on LFW dataset. Due to limitation of computing power, I can not train the model for the moment. This is real."""

Even codes from sklearn or google, I can figure out some problems from codes. Did you mean that I SHOULD NOT **ask questions?** If that is true, fuck you bitch. If that is not true, since you are not the owner and don't understand the question I am talking about, while give no  POSITIVE response, I suggest you SHUT UP.

I HAVE SAID frequently, DON'T MAKE IT PERSONAL!  

> In open source world, the more you do, the more work you will get. -- Linux

CAN you understand WHAT IS RESPONSIBILITY? 

> You released a project before the number of stars goes up, which means some other people might choose to trust you with their own risk of time and money.  -- A famous open source developer

You disgusted me with prejudice remarks. A well educated person will not answer question in that manner.
