### ISSUE TITLE
There may be some errors in the 'labels'

### ISSUE THREAD

**Issue by luoyong87** [AlfredXiangWu/face_verification_experiment#144]
I run your 'evaluation.m' demo and found that there may be some in the 'labels':

1. There are only 5745 persons in the 'labels', but LFW has 5749 persons;
2. The person with label '17' has only 19 images, but in your 'labels', there are 20 samples (sample 31 to 50), so there may be some errors in your created 'pos_pair' and 'neg_pair'.

**Comment by AlfredXiangWu** [comment]
There is something wrong about the label, but it doesn't influence the evaluation of the LFW 6,000 pairs because the label are not used in the evaluations nor to create the positive and negative pairs. You can compare the created pairs with the official 6,000 pairs by names.

**Comment by luoyong87** [comment]
For the first positive pair (57, 60), it seems that the 57th image is 'Abel_Pacheco_0002.jpg', and the 60th image is 'Abid_Hamid_Mahmud_Al-Tikriti_0001.jpg'. They are not the same person. Could you share me your image list when you extract your features? Thanks!

**Comment by AlfredXiangWu** [comment]
The mat file of features has already contained the image list of lfw.
