### ISSUE TITLE
Xavier vs Gaussian

### ISSUE THREAD

**Issue by beppe2hd** [AlfredXiangWu/face_verification_experiment#146]
Hi, first of all thanks for providing all the model and prototxt.
I have a simple question: on the paper you state "The parameter initialization for convolution is Xavier and Gaussian is used for fully connected layers"
Anyway, in all the three prototxt files reported here the Xavier is employed for the convolution too? Which is the correct solution?

Many thanks

Marco

**Comment by AlfredXiangWu** [comment]
For the latest version, we use xavier for both convolution and fully-connected layer.
