### ISSUE TITLE
I feel the size of the trainning data doubt 

### ISSUE THREAD

**Issue by xuezhongcailian** [AlfredXiangWu/face_verification_experiment#147]
Hello,Mr Wu,I read your paper and see your github code ,what I want know your trainning set input is 144*144 or 128*128? I am puzzled to size of trainning and testing set. because I feel the paper is not in line with   the description section of repository,could you tell you about this problem?

**Comment by AlfredXiangWu** [comment]
When training, the 144x144 face image is randomly cropped into 128x128 as the input.
