### ISSUE TITLE
no an issue but a doubt

### ISSUE THREAD

**Issue by shashankvkt** [AlfredXiangWu/face_verification_experiment#148]
Hello sir,
Using your caffemodel(A) trained on casia webface database..I actually wanted to extract features using matcaffe by first loading the model(Deploy) and the weights of model A.
while doing so i create a variable 
    net = caffe.Net(model, weights, 'test');
to compute the features i do, feats = net.forward({img});

but the output of the feats variable are all zeros. Could you kindly guide me to find a solution.

Thank you.

**Comment by AlfredXiangWu** [comment]
The model A and B were trained on caffe-rc two years ago. It seems the interfaces of matcaffe and the details of implements are different between caffe-rc and caffe-1.0. So the released model A is not used by the current caffe version. 

I suggest you use the model C which is trained on caffe-rc3.

**Comment by shashankvkt** [comment]
Cool thank you
