### ISSUE TITLE
about lfw labels in model C-LightenedCNN_C_lfw.mat

### ISSUE THREAD

**Issue by DCore-2046** [AlfredXiangWu/face_verification_experiment#149]
First, thank you for sharing the model.
when I load LightenedCNN_C_lfw.mat,labels array[4:7]=[3 3 3 3], and file_path[4:7]=[Aaron_Guiel Aaron_Patterson Aaron_Peirsol_1 _2 _3];
there are some samples flag some label but belong different class.
there are some wrong or some info I do not get.

**Comment by DCore-2046** [comment]
sorry, there are some samples flag same label but belong different class.

**Comment by AlfredXiangWu** [comment]
Refer to issue https://github.com/AlfredXiangWu/face_verification_experiment/issues/144

**Comment by DCore-2046** [comment]
thanks
