### ISSUE TITLE
5pt NOT exists

### ISSUE THREAD

**Issue by tianboguangding** [AlfredXiangWu/face_verification_experiment#15]
Thanks for your model！
But i have some problems in using face_db_align.m to align myself's samples。
 Is ffp_dir  the face_five_point? 
 And  after I use Yi Sun's work to extract landmark, the samples's results were saved in a binary file （result.bin）.

As I use the first function :
function res = face_db_align(face_dir, ffp_dir, ec_mc_y, ec_y, img_size, save_dir),

The error message is followed：
D:\github\Five_point_detector\code_point\image.\2000002_1493.5pt NOT exists.
??? Undefined function or variable "resize_scale".
Error in ==> face_db_align at 50
        fprintf(log_fid, '%s %f\n', ffp_fn, resize_scale);

How do I use the result.bin?
Which function do i choose is correct?

Thanks very much!

**Comment by AlfredXiangWu** [comment]
I am sorry to reply you so late.

Actually, the Yi Sun's code can get the result.bin which could not be used directly. If you want to use my code to do alignment, you should transform the result.bin to the '.5pt' file. The format of '.5pt' file is as follows:
x_(left eye) y_(left eye)
x_(right eye) y_(right eye)
x_(noise) y_(noise)
x_(left mouth corner) y_(left mouth corner)
x_(right mouth corner)) y_(right mouth corner)

The file structure of facial points file is followed as the structure of images, for example, 
lfw/image/Aaron_Eckhart/Aaron_Eckhart_0001.jpg  
lfw/image/Aaron_Eckhart/Aaron_Eckhart_0001.5pt

Moreover, according to others' email, reproducing my result on LFW is not necessary to perform face alignment as my method. Other similar alignment pre-processing on face images is OK.
