### ISSUE TITLE
MegaFace Evaluation: it generated 'OpenCV Error' when running experiment.py with own features

### ISSUE THREAD

**Issue by staceycy** [AlfredXiangWu/face_verification_experiment#154]
Hi Mr. Wu,

Thanks for your sharing your work and ideas on MegaFace Verification. 

Currently, I want to test my own face recognition model with MegaFace dataset(FGNET). After generating my own features, I run it with the Development Kit provided by the official site, but the experiment.py showed the following errors:

OpenCV Error: Insufficient memory (Failed to allocate 18384280673610776056 bytes) in OutOfMemoryError, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/alloc.cpp, line 52

My feature for a single image is of size 8 kb, which contains a vector of length 2048, which is much smaller than the public available feature of size 100*!00 (27kb). 

Could you please give me some advice on how to proceed to find or fix the problem? Looking forward to your reply. 

Thank you.

**Comment by runningJ** [comment]
i meet the same problem. are you resolved it ?
