### ISSUE TITLE
can't get the same result

### ISSUE THREAD

**Issue by CLIsVeryOK** [AlfredXiangWu/face_verification_experiment#156]
I tried the caffeModel in the folder in matlab, but I can't get discriminative face feature as folder results. I wonder if any preprocessing needed? I cropped the image in 128x128 and The distance between the
midpoint of eyes and the midpoint of mouth are set to 48 pixels and the y axis of midpoint of eyes is set to 40. then use the 128x128 uint8 image as input. but the feature I get has a close cosine distance(>0.9) even the input are different people.

**Comment by hshunghsu** [comment]
hi CLIsVeryOK
How to convert the image  to the distance between the midpoint of eyes and the midpoint of mouth are set to 48 pixels and the y axis of midpoint of eyes is set to 40

**Comment by it-jiao** [comment]
Hello, CLIsVeryOK, @AlfredXiangWu have you solved the problem? I have the same problem with you.

**Comment by AlfredXiangWu** [comment]
I think the problem is normalization of input. You should normalize the image from [0, 255] to [0, 1].
