### ISSUE TITLE
Using matlab extracted feature by off the shelf caffemodel, but validation set is only 73%.

### ISSUE THREAD

**Issue by Wyyghst** [AlfredXiangWu/face_verification_experiment#17]
First, thank you for your contribution。

I write matlab code to extracting features and L2 Classification for LFW dataset. But only get 73% verification correct rate. The caffemodel and deploy.prototxt are provided by you.

The matlab code is:

``` matlab
dr_lfw_features = [];
for i= 1:length(fileLines)
    im = imread( fileLines{i} );    
    im = rgb2gray(im);
    im = imresize(im, [128 128]);
    im = single(im);
    im = im /256.0;
    im = im';

    blob_index_drop = net.name2blob_index('dropout1');%feature blob
    blob_drop = net.blob_vec(blob_index_drop);  
    net.forward({im});
    fprintf('iamge is %s, i = %d\n', fileLines{i}, i);
    blob_drop_data = blob_drop.get_data();
    blob_drop_data = reshape(blob_drop_data, 1, 256);
    dr_lfw_features = [dr_lfw_features; blob_drop_data];
end

load('dr_lfw_features.mat');
test_Intra = pairlist_lfw.IntraPersonPair;
test_Extra = pairlist_lfw.ExtraPersonPair;
test_pair = [test_Intra; test_Extra];

F1_index = test_pair(:,1);
F2_index = test_pair(:,2);

AllFeature1 = dr_lfw_features(F1_index, :);
AllFeature2 = dr_lfw_features(F2_index, :);

num = length(AllFeature1);
F1 = AllFeature1;
F2 = AllFeature2;
thresh2 = zeros(num,1);
for i = 1:num
    thresh2(i) = - sum((F1(i,:)/norm(F1(i,:)) - F2(i,:)/norm(F2(i,:))).^2);
end;
figure;
hist(thresh2(1:3000),500);
figure;
hist(thresh2(3001:end),500);

accuracies = zeros(1,1);
for i=1:10
    test_idx = [(i-1) * 300 + 1 : i*300, (i-1) * 300 + 3001 : i*300 + 3000];
    train_idx = 1:6000;
    train_idx(test_idx) = [];
    bestc=256;
    same_label = ones(6000,1);
    same_label(3001:6000) = 0;
    cmd = [' -t 0 -h 0'];
    model = svmtrain(same_label(train_idx),thresh2(train_idx),cmd);
    [class, accuracy, deci] = svmpredict(same_label(test_idx),thresh2(test_idx),model);
    accuracies(i) = accuracy(1);
end;
mean(accuracies)
cmd = [' -t 0 -h 0'];
model = svmtrain(same_label,thresh2,cmd);
[class, accuracy, deci] = svmpredict(same_label,thresh2,model);
```

By hist histogram, you can see the same data threshold and different data threshold obviously inseparable.
I think there are errors in this matlab, do you have any good suggestions?

**Comment by AlfredXiangWu** [comment]
1. im = imresize(im, [128 128]);
   Do you do pre-processing for images of the LFW dataset? If you don't, maybe the results would be dropped.
2. blob_index_drop = net.name2blob_index('dropout1');
   The feature layer is eltwise6. I have never used the matcaffe, therefore, I don't know whether the dropout layer makes effect when extracting features. If it works, the feature is wrong. 
3. I don't know why you use svm. If you want to reproduce the results of our model, I think you need to evaluate the results according to the test protocol of LFW(http://vis-www.cs.umass.edu/lfw/#views). 
   The scores of test pairs are computed by cosine similarity directly, and then the performance is evaluated by ROC curve.

**Comment by Wyyghst** [comment]
thank you for your reply.
1. I used LFW data that all images aligned with deep funneling(111MB), downloaded from LFW official website without other preprocessing.
2. I tested two kind feature 'dropout1' and 'eltwise6', but the result does not change.

3.

``` matlab
accuracies = zeros(1,1);
for i=1:10
    test_idx = [(i-1) * 300 + 1 : i*300, (i-1) * 300 + 3001 : i*300 + 3000];
    train_idx = 1:6000;
    train_idx(test_idx) = [];
    bestc=256;
    same_label = ones(6000,1);
    same_label(3001:6000) = 0;
    cmd = [' -t 0 -h 0'];
    model = svmtrain(same_label(train_idx),thresh2(train_idx),cmd);
    [class, accuracy, deci] = svmpredict(same_label(test_idx),thresh2(test_idx),model);
    accuracies(i) = accuracy(1);
end;
mean(accuracies)
```

This svm code is intended to do 10-fold cross validation. 
I refer of other people's code( https://github.com/happynear/FaceVerification/blob/master/lfwL2.m )
And, I don't think there is a problem this code.

Before svm classification codes, I display L2 threshold histogram.

``` matlab
figure;
hist(thresh2(1:3000),500);
figure;
hist(thresh2(3001:end),500);
```

![default](https://cloud.githubusercontent.com/assets/13027621/11110748/1143f26c-893b-11e5-8465-e7cd08e28145.png)

The picture on the left is the same person histogram threshold value, the right is different. you can see that obviously inseparable. (Horizontal axis is threshold, Vertical axis is frequency)

And, I run your evaluation.m code, features is in 'lfw_man5pt.mat', display 'pos_scores' and 'neg_scores' histogram.

``` matlab
figure;
hist(pos_scores, 500);
figure;
hist(neg_scores, 500);
```

![1](https://cloud.githubusercontent.com/assets/13027621/11110830/11706116-893c-11e5-83a0-9e5bb7855c8f.png)

Obviously, this result is divisible.

So, since your caffemodel is right, I think the problem is in processing LFW data or MATLAB feature extraction code section. Do you have any good suggestions?

```
                                                                                                                                             Thanks.
```

**Comment by AlfredXiangWu** [comment]
The problem may be feature extraction by Matlab. Did you compare the features extracted by Matlab with the ones by cpp?
Different alignment methods may lead to the performance dropped only 1%~2% as far as I am concerned.
