### ISSUE TITLE
The question of face detection

### ISSUE THREAD

**Issue by Wyyghst** [AlfredXiangWu/face_verification_experiment#21]
First, thank you for your contribution.
I use the modelB to reproduce the LFW face verification experiment. In the preprocessing stage, I use code_face to generates bbox file. But there are 157 pictures no detected bbox, and 580 pictures have multiple bboxes. So, I set  fixed position and size bboxes for all no detected bbox pictures. And I selected the largest area bbox for multiple bboxes pictures.
Ten-fold cross-validation results is 96%, lower than 98.13% of your result.
So I want to know how do you handle these two cases？

By the way, In the windows system, lfw_pairs.mat that provided by you does not match images sort by name. for example the first pair of pos_pair is 57 60, but they are not the same people. So, I use the pairs.txt download from LFW official website to generating pairs file. Do you encountered this problem?
                                                                                                                                           Thanks.

**Comment by AlfredXiangWu** [comment]
I fixed the detection and facial point extraction error  by hand. 

I checked my lfw_pairs.mat file. The 57 index is opposite to the image "lfw/image/Abel_Pacheco/Abel_Pacheco_0001.bmp" and the 60 index is opposite to the image "lfw/image/Abel_Pacheco/Abel_Pacheco_0004.bmp". Obviously, these two images are the same person. You can use matlab to load the LightenedCNN_A_lfw.mat or LightenedCNN_B_lfw.mat  which includes "features", "labels", "labels_original" and "image_path". Then you can check the image_path by lfw_pairs.mat file.

**Comment by Wyyghst** [comment]
Thanks for your reply.
"I fixed the detection and facial point extraction error by hand." Do you mean that manually check all LFW data?
Before training CNN, Do you also manually checked all CASIA data?

**Comment by AlfredXiangWu** [comment]
I don't check the CASIA-WebFace data about the detection errors, landmark errors and even the label errors,  but I think if it is done, the performance will be imrpoved.
