### ISSUE TITLE
feature extracted difference

### ISSUE THREAD

**Issue by zlinker** [AlfredXiangWu/face_verification_experiment#22]
Hi, @AlfredXiangWu , I've trained a model following your paper, it works  and shows good performance  on valid set of casia_webface. 

However, the performance on verific task was bad. I tried to use your release model and extract features from the lfw set. They queit difference from your released .mat features, and the accuracy was about 63%. 

I think my alignment work was finished well using my reimplement of "Deep convolutional network
cascade for facial point detection" and your code face_db_align.m. Are there some extra works should be done when extracting the features? Thanks.

**Comment by AlfredXiangWu** [comment]
The accuracy you obtained is abnormal. 
Do you convert the value of pixels from [0, 255] to [0, 1]?

**Comment by zlinker** [comment]
okay…I did miss this preprocess step, it can reach about 93% on verification experiment now, thank you.
