### ISSUE TITLE
您好，我尝试训练您的CNN遇到困惑

### ISSUE THREAD

**Issue by gzp001015** [AlfredXiangWu/face_verification_experiment#29]
首先感谢大神共享网络参数，我严格按照您的步骤，首先用港大的两个工具生成了人脸特征点文件，然后用您的matlab程序对齐了人脸，对齐的结果是有接近6W张无法检测到人脸或无法对齐或有多张人脸，我全部按照中心裁剪成144*144，剩下的可以对齐但与您论文的样例稍有差距，感觉上左右都比论文上多出了5-8个像素，请问这个误差怎么来的呢。
其次，我是采用每个目录的第一张做验证，现在最高能在softmax上达到74.355的test识别率，远远达不到85%-92%的区间内，请问是我训练有问题还是我选验证集的方式和您有出入？
还有，我在最后两个全链接层的初始化方法用 type: "gaussian"，fc1用0.005 fc2用0.01，识别率低是否和这个有关？
望大神在百忙之中不吝赐教！！！！感谢

**Comment by AlfredXiangWu** [comment]
1. 关键点提取的方法我只是建议用孙祎的那个，我自己用的是他的算法但是模型是重新训练的，因此可能有些关键点会有稍微的偏差。
2. 有可能是验证集选择的问题，个人认为不需要特别纠结验证集的准确率，毕竟我们测试时是提取fc1的特征层然后计算cosine距离，从fc1到fc2之间的一大堆参数都是被抛弃的，因此直接提特征看lfw的准确率更有说服力
3. 可能和gaussian有关，因为gaussian初始化要预设std，这个值给不好很可能导致网络收敛不好，微软15年年初一篇关于imagenet的论文专门分析过初始化的问题，你可以参考一下。

**Comment by gzp001015** [comment]
非常感谢 ，我还想问下 您的验证集是从数据集中分离剪切走的还是拷贝走的，也就是说您是否用了全部webface来训练

**Comment by AlfredXiangWu** [comment]
用了全部数据做训练，训练集包含验证集

**Comment by gzp001015** [comment]
万分感谢
