### ISSUE TITLE
Identify people with glasses

### ISSUE THREAD

**Issue by zirohut** [AlfredXiangWu/face_verification_experiment#32]
Hi everyone.

I'm recently implementing face verification in video surveillance. I'm using CASIA as training data and the CNN network mentioned in the CASIA paper. Although the model get 96% on LFW, there are still problems in real life situations. Now I'm facing the glass block problem. The model is often confused by people with similar thick black framed glasses. It can't separate their identities apart. This has been bugging me for two weeks and I hasn't come up with a robust solution yet.

Any thoughts?

**Comment by AlfredXiangWu** [comment]
The deep learning based methods such as CNN are often data-driven model. Therefore, to some degree, the more training data you used, the higher performance you obtained. 

In my opinion, you could collect some face images with glasses or do data augmentation for training data, for example, shading the eyes according to the facial points manually. And I think the former one is more efficient but may pay much time. 

BTW, I think the LFW accuracy doesn't stand for the performance of face recognition system in practice.
