### ISSUE TITLE
人脸上五个点的坐标是怎么得到的？

### ISSUE THREAD

**Issue by Tonyfy** [AlfredXiangWu/face_verification_experiment#35]

**Comment by AlfredXiangWu** [comment]
http://mmlab.ie.cuhk.edu.hk/archive/CNN_FacePoint.htm
用这个方法跑出来的landmark

**Comment by Skywalkerfh** [comment]
检测人脸上的五点的时候出现了，Warning：roi exceed the original image, 这是不是代表五点的坐标超出了原始图像尺寸？请教一下博主您当时有没有出现这种情况，如果有的话，您是怎么处理这些数据的。谢谢！

**Comment by AlfredXiangWu** [comment]
直接跑就好了，我是跑完了以后人工检验的

**Comment by Skywalkerfh** [comment]
谢谢博主，alignment已经做好了，我现在用这些数据在训练vgg-16的网络，已经训练了3天了，但是分类错误率（错误率一直在百分之九十多）和损失函数一直不见下降，learning rate和batchsize我都调整过，也做了random crop依然没什么效果，博主您对这种情况有没有什么建议啊，另外您的这个模型跑了多久最终训练好得？特别感谢！

**Comment by AlfredXiangWu** [comment]
额，注意仔细看vgg-16那篇论文，要先训练浅层网络，然后用浅层网络的结果初始化深层网络才比较容易收敛。我没试过那么深的网络，我觉得直接train可能比较难收敛，另外关于深层网络收敛难的问题可以关注MSRA最近关于Deep Residual Learning的一系列工作

**Comment by Skywalkerfh** [comment]
好的，非常感谢。

2016-03-21 

blackbest 

发件人：Alfred Xiang Wu notifications@github.com
发送时间：2016-03-21 10:45
主题：Re: [face_verification_experiment] 人脸上五个点的坐标是怎么得到的？ (#35)
收件人："AlfredXiangWu/face_verification_experiment"face_verification_experiment@noreply.github.com
抄送："Skywalkerfh"blackbest@163.com

额，注意仔细看vgg-16那篇论文，要先训练浅层网络，然后用浅层网络的结果初始化深层网络才比较容易收敛。我没试过那么深的网络，我觉得直接train可能比较难收敛，另外关于深层网络收敛难的问题可以关注MSRA最近关于Deep Residual Learning的一系列工作

**Comment by Tonyfy** [comment]
那么工具标不出或者标错的图片，就不用于训练吗？人工量好大呀：）
