### ISSUE TITLE
pool4 layer in ModelB

### ISSUE THREAD

**Issue by cheer37** [AlfredXiangWu/face_verification_experiment#37]
@AlfredXiangWu 
You mentioned 5 pooling layers in B model in the paper.
However, there are only 4 pooling layers in the prototxt you posted.
Why different? which is more correct?
Thanks.

**Comment by AlfredXiangWu** [comment]
There are some typos in the paper. The released project on Github is correct, when encountering anything which are different between paper and released model.

**Comment by cheer37** [comment]
Thank you.
