### ISSUE TITLE
Fine-tuning the B model.

### ISSUE THREAD

**Issue by cheer37** [AlfredXiangWu/face_verification_experiment#40]
@AlfredXiangWu 
I am trying to do fine-tuning your B model.
I imitated your alignment and training method. but it's the same as training from first without model.
Loss starts from 25.70 and accuracy starts from 0.
What's the reason?
Thanks.

**Comment by AlfredXiangWu** [comment]
Fine-tune my model on CASIA-WebFace? The "fc2" is 10575?

**Comment by cheer37** [comment]
yes, it's 10575

**Comment by AlfredXiangWu** [comment]
Oh, I am sorry that I have no idea about the problem. Maybe it is caused by different caffe version. The caffemodel is trained by caffe-rc.

**Comment by cheer37** [comment]
I see. Thanks.

**Comment by cheer37** [comment]
Would you check if my situation raises at you when fine tuning with latest caffe version?
Thanks.

**Comment by facerless** [comment]
My train loss  starts from 55.
