### ISSUE TITLE
where is meanfile?

### ISSUE THREAD

**Issue by iscas-lee** [AlfredXiangWu/face_verification_experiment#41]
hi Wu , i cannot find the meanfile of this LightenedCNN_A.caffemodel.

**Comment by AlfredXiangWu** [comment]
The network is trained without mean file.

**Comment by mariolew** [comment]
You mean both two networks were trained with raw pixel, without sub the mean?

**Comment by AlfredXiangWu** [comment]
@mariolew Yes, I only convert image pixel value from [0, 255] to [0, 1].

**Comment by iscas-lee** [comment]
can u show me  how to use your model  to compute the distance of two faces ?

**Comment by cheer37** [comment]
You have to extract features of two faces firstly in eltwise6 layer.
Then compare two feature vectors using Euclidean distance or Cosine distance.

**Comment by iscas-lee** [comment]
Is there a feature extraction demo can refer to? 
For Caffe, I am a novice. C++ or matlab code is better.

**Comment by cheer37** [comment]
Refer to cpp_classification in examples in caffe.

**Comment by iscas-lee** [comment]
It ' s very kind of you. I'm trying to do it.
