### ISSUE TITLE
matlab的提取特征计算两个分数跟你的差距有点大

### ISSUE THREAD

**Issue by iscas-lee** [AlfredXiangWu/face_verification_experiment#43]
Hi Wu, 我用你Amodel 提取特征然后用： cosTheta = dot(u,v)/(norm(u)*norm(v)) 计算，分数好像有些问题，估计是特征提取错误了。

以下是我的matlab的代码，请教下是否正确？

> function [feature]  = VerificationDemo2( image_file_1 )
> addpath('E:\face\caffee\caffee-windows\caffe-windows\matlab\');
> if ~exist('model_inited','var')||~model_inited
> caffe.reset_all();
> caffe.set_mode_cpu();
> 
> same_thresh = 0.4;
> 
> MatAlignment('init_model','E:\ThirdPartyLibrary\dlib-18.14\shape_predictor_68_face_landmarks.dat');
> net_model = 'E:\face\caffee\caffee-windows\caffe-windows\matlab\face_verification_experiment\proto\LightenedCNN_A_deploy.prototxt';
> net_weights = 'E:\face\caffee\caffee-windows\caffe-windows\matlab\face_verification_experiment\model\LightenedCNN_A.caffemodel';
> 
> net = caffe.Net(net_model,net_weights, 'test');
> model_inited = true;
> model_inited64 = false;
> end;
> image1 = rgb2gray(imread(image_file_1));
> 
> J = zeros(height,width,1,20,'single');
> 
> face1 = MatAlignment('alignment',image1);
> face1 = imresize(face1,[width height]);
> 
> I = single(face1)/256;
> J(:,:,1,1) = I;
> %net.set_input_scale('data', 20)
> feature_size = 256;
> feature_test = [];
> H={J};
> fea = net.forward(H);
> % 特征层对于A是eltwise6，对于B是eltwise_fc1
> output_blob_index = net.name2blob_index('eltwise6');%feature blob
> output_blob = net.blob_vec(output_blob_index);
> output = output_blob.get_data();
> feature =output(:,1);
> end

尤其是这个地方，

> J = zeros(height,width,1,20,'single');

如果我写成zeros(height,width,1,1,'single'); 就会报

> input data/diff size does not match target blob shape, input data/diff size: [ 128 128 1 1 ] vs target
> blob shape: [ 128 128 1 20 ]

**Comment by AlfredXiangWu** [comment]
> name: "DeepFace_set003_net"
> input: "data"
> input_dim: 20
> input_dim: 1
> input_dim: 128
> input_dim: 128

第一列input_dim相当于输入的batch_size，这里写20那你肯定一次要给20张图片，这样才能在网络check参数的时候对应上，你改成1肯定会报错

> input data/diff size does not match target blob shape, input data/diff size: [ 128 128 1 1 ] vs target
> blob shape: [ 128 128 1 20 ]

这个错误本身也说得很明确了

结果不对请check下数据预处理是否有问题，预处理不当会造成结果drop

**Comment by iscas-lee** [comment]
奥，谢谢了。
那我可以 直接将batch_size改为1的吧？
name: "DeepFace_set003_net"
input: "data"
input_dim: 1
input_dim: 1
input_dim: 128
input_dim: 128
