### ISSUE TITLE
Share the training logs

### ISSUE THREAD

**Issue by cheer37** [AlfredXiangWu/face_verification_experiment#44]
I want to see your training logs of A and B to check if my training goes well or not.
And also, have you tried with RGB image instead of Gray Image?
Why didn't you specify the param about lr_mult and decay_mult in fc2 in B model?
Without specifying them, how does net work? And how did you set it in your training.
Thanks.

**Comment by AlfredXiangWu** [comment]
Sorry, I am on business. I would provide the log as soon as possible

"Weight_decay" is L2 regularization for neural network. According to my experiments, the net also works and the performance would not be dropped without specifying them .

**Comment by cheer37** [comment]
ok, thx
