### ISSUE TITLE
关于模型的两个问题

### ISSUE THREAD

**Issue by mengfanr** [AlfredXiangWu/face_verification_experiment#45]
老师您好 
首先我想请问下 文章中进行测试时是对于LFW的原始数据集进行的特征点定位还是说根据deep funneled的图片进行的特征点定位呢
其次 readme里面写的利用caffe_ftr.py进行特征提取 但是我们在运行文件的时候提示说  'Classifier' object has no attribute 'set_phase_test'

**Comment by AlfredXiangWu** [comment]
1. 根据原图进行关键点定位
2. 具体看一下caffe的python接口吧，这个提特征的代码是很早以前写的，期间官方caffe的python接口做过很多修改，对应着新版本自己修改吧

**Comment by mengfanr** [comment]
1、也就是说我们在原图上进行特征点标定 然后在按照论文的要求对两眼中间距离到嘴的距离进行校正  最后在提取特征的时候进行图片的resize缩放是吗？
2、好的 我对应官方的看下 谢谢老师

**Comment by mengfanr** [comment]
还有个问题是  我们只想要利用论文提供的模型来进行特征提取，不知道能不能直接利用lfw已经调整好的图片直接提取特征呢？

**Comment by AlfredXiangWu** [comment]
可以直接用release的模型提取特征的，不过要注意我的模型使用caffe-rc训练的，所以我不保证在caffe-rc2或者caffe-rc3上提取出来的特征一定正确，如果要直接用model建议使用caffe-rc版本

**Comment by mengfanr** [comment]
好的 谢谢老师  我想再问下 我是直接down的caffe-master 并没有使用rc版本 这有影响吗？

**Comment by AlfredXiangWu** [comment]
现在caffe master brach下的code肯定不是caffe-rc了，去release里面看吧

**Comment by mengfanr** [comment]
谢谢您  现在我已经编译好了rc版本了 但是用matlab程序跑的时候 没能理解deploy的
input_dim: 20
input_dim: 1
input_dim: 128
input_dim: 128
第一个20是不是每个image对应10个 然后还要mirror image 然后再来十个？

**Comment by mengfanr** [comment]
如果按照上面所说 input_dim=20的话 那为啥提供的特征是256维的呢 应该是256*20维的啊？

**Comment by AlfredXiangWu** [comment]
第一个input dim是batch size的大小，具体内部实现细节可以直接看caffe源码
