### ISSUE TITLE
EER && accuracy.measure不相等

### ISSUE THREAD

**Issue by tianboguangding** [AlfredXiangWu/face_verification_experiment#51]
hi，吴老师：
看您评估代码../face_verification_experiment/code/+evaluation/里有 +accuracy这一项，于是我就在evaluation.m加了句：
accuracy=evaluation.evaluate('accuracy',scores,label);
当载入您的LightenedCNN_A_lfw.mat时，EER和accuracy.measure都是97.77%（LightenedCNN_B_lfw.mat也都是98.13%）。
但如果通过载入模型LightenedCNN_A.caffemodel所提取出的特征mat时，测试其EER：96.87%，accuracy.measure：97.05%。

1.EER && accuracy.measure不相等
2.低于97.77%是什么原因呢？

多谢！

**Comment by tanzf** [comment]
你好@tianboguangding，我想问一下你训练使用的CASIA-WebFace，是怎么分的训练集和测试集的，CASIA-WebFace的50万幅图像全用上了吗？，万分感谢

**Comment by yxu0611** [comment]
@tanzf 
同问这个问题。
我现在是每一个identity随机选一个图像作为测试，剩下的作为训练。
测试数据集，# of identity: 10575, # of image: 10575
训练数据集, # of identify: 10575, # of images: 483839
@tianboguangding

**Comment by tanzf** [comment]
@yxu0611 你好，你能把你剪裁对齐之后图像发我一份吗？我对齐之后还剩下40万副了，好少，这是我的邮箱tanzfzb@163.com，万分感谢

**Comment by yxu0611** [comment]
@tanzf 不好意思，这个不可以，请谅解。
另，训练数据是用全部的casia web face，它与测试的数据有overlap
