### ISSUE TITLE
请问提取特征的时候 需要设置transform的scale参数为0.00390625吗？

### ISSUE THREAD

**Issue by yzk0281** [AlfredXiangWu/face_verification_experiment#55]
Hi，Sir Wu
请问提取特征的时候 需要设置transform的scale参数为0.00390625吗？

**Comment by AlfredXiangWu** [comment]
这个需要看你提取特征的代码具体是怎么实现的，如果是调用我提供的python代码是不需要的，因为里面读取出的图像已经是0~1范围内了。
