### ISSUE TITLE
where is the mean.binary

### ISSUE THREAD

**Issue by gxcLe** [AlfredXiangWu/face_verification_experiment#57]
hi I test your model and the acc result is about 85%, i imagine if the mean-value was missing?

**Comment by AlfredXiangWu** [comment]
I don't use mean file for training and testing.

**Comment by gxcLe** [comment]
thankyou for your reply. just now I test the model again,get the result of 0.958 acc,i remember your result is 0.98+. I used the cos-dis for face verification, I wonder if I lost some detials. looking forward to your reply, ths!
