### ISSUE TITLE
C++提取特征

### ISSUE THREAD

**Issue by niewuya** [AlfredXiangWu/face_verification_experiment#58]
你好，我的是caffe的最新版本，用C++提取eltwise6层的特征，得到的特征值正负都有，不是稀疏特征值，求余弦距离发现不管是不是同一个人，余弦值都是0.8以上，不知道哪一步错误了呢？或者是caffe版本不一样的问题？非常感谢楼主。

**Comment by dejunzhang** [comment]
遇到同样的问题，请问是什么地方出错了？
特征提取我是在classification.cpp代码的基础上修改的.
