### ISSUE TITLE
Data pre_processing: face alignment

### ISSUE THREAD

**Issue by ForeverGaara** [AlfredXiangWu/face_verification_experiment#6]
Hi~, I would like to use the "face_db_align.m" to process the original CASIA-Webface database, but I have no 5 facial point files, would you like to share the landmarks files, thank you so much!

**Comment by AlfredXiangWu** [comment]
You can use Yi Sun's code to extract the 5 facial points.
http://mmlab.ie.cuhk.edu.hk/archive/CNN_FacePoint.htm
