### ISSUE TITLE
face identification much bad

### ISSUE THREAD

**Issue by twinsyssy1018** [AlfredXiangWu/face_verification_experiment#62]
hi, i  used the model and do face identification with the dataset metioned in the paper, but the accuracy is only 43% (for close-set),   could you tell me what is wrong?  what have to be done for the preprocessing?

**Comment by AlfredXiangWu** [comment]
Do you use the features I provided for the close-set evaluation? If not, I think you may do it to check your evaluation code. 

The details of data pre-processing are written in the Readme. The example of aligned image is shown in issue https://github.com/AlfredXiangWu/face_verification_experiment/issues/4. You could compare it with your aligned images.

**Comment by twinsyssy1018** [comment]
thank you. i can not find the features you provided for the close-set evaluation. only lfw features in the result file.               my aligned images are indeed different , which aligned tool do you use?  
best wishes.
