### ISSUE TITLE
关于Joint Bayesian

### ISSUE THREAD

**Issue by jiangxuehan** [AlfredXiangWu/face_verification_experiment#63]
@AlfredXiangWu  请问有没有测试过Joint Bayesian的提升作用？ 我尝试使用Joint Bayesian对CNN特征进一步训练，效果不仅没有提升，还有略微下降，感觉不太正常。 (使用LBP+JB效果还是很明显的，所以很困惑，deepID里面JB的作用还是很明显的)

**Comment by AlfredXiangWu** [comment]
用joint bayesian确实会下降，应该是overfitting了。
如果你仔细看细节，joint bayesian work的LBP和deepID中，给jb的特征都是高维特征，LBP不说了，deepID也是一堆patch拼起来的特征送给jb的，所以我认为这样的特征中还有些冗余信息，通过jb可以提升最终的性能，而我的特征就只有256维，可能送给jb就不work了，当然这只是我的猜测。具体你可以自己做实验验证一下

**Comment by BeginnerW** [comment]
@jiangxuehan 能说说你的联合贝叶斯训练前后的LFW精度分别是多少吗？特征是如何选取的？谢谢了

**Comment by jiangxuehan** [comment]
@BeginnerW  具体的值时间太久忘记了 原始的可以参考这里的结果 JB之后可能下降了0.5%~1%吧。我用的单模型 不存在特征选择问题。
