### ISSUE TITLE
could you provide one image of lfw aligned?

### ISSUE THREAD

**Issue by twinsyssy1018** [AlfredXiangWu/face_verification_experiment#64]
my result is 96.4% on lfw and  the same model .i have compared the feature you provided , but much  different with mine..i think there must be something different of the aligned images. could you upload one or two images . thank you

**Comment by AlfredXiangWu** [comment]
The example of aligned face image is as follow. 
![aaron_eckhart_0001](https://cloud.githubusercontent.com/assets/6490849/16640950/c98ae624-442e-11e6-8ac0-8103371c66ca.jpg)

**Comment by twinsyssy1018** [comment]
thank you very much

**Comment by twinsyssy1018** [comment]
thank you.. but i checked the distance of ec_y,ec_mc_y.  ec_y is 40,but ec_mc_y is almost 45, look:
![2016-07-07 11 15 54](https://cloud.githubusercontent.com/assets/14009379/16641590/dc1091f8-4434-11e6-8350-edfda350ba57.png)     the 5 points detected by https://github.com/luoyetx/deep-landmark [a reimplementation of the paper Deep Convolutional Network Cascade for Facial Point Detection.]

**Comment by twinsyssy1018** [comment]
i have found my mistake, i set the ec_y=ec_mc_y=48.. thank you very much!

**Comment by tpys** [comment]
@twinsyssy1018 haha
