### ISSUE TITLE
Error in executing caffe_ftr.py

### ISSUE THREAD

**Issue by amirid** [AlfredXiangWu/face_verification_experiment#67]
Hi,
I encountered the following error while I was trying to run the caffe_ftr.py:

F0830 04:42:46.029270 7922 insert_splits.cpp:29] Unknown bottom blob 'label' (layer 'accuracy', bottom index 1)
**\* Check failure stack trace: ***
Aborted (core dumped)

I want to extract features from some aligned images. I did the instruction written in caffe_ftr.py .

**Comment by AlfredXiangWu** [comment]
> F0830 04:42:46.029270 7922 insert_splits.cpp:29] Unknown bottom blob 'label' (layer 'accuracy', bottom index 1)

As is shown in the error message, I think you could use deploy.prototxt to extract features via the python code instead of train_test.prototxt
