### ISSUE TITLE
Training for my own dataset

### ISSUE THREAD

**Issue by wajihullahbaig** [AlfredXiangWu/face_verification_experiment#68]
Dear Wu
I want to create my own "LightenedCNN_A.caffemodel", any chance of you providing the solver files on which you created the models?

**Comment by AlfredXiangWu** [comment]
> net: "DeepFace_set003_train_test.prototxt"
> 
> test_iter: 500
> test_interval: 1000
> test_compute_loss: true
> 
> base_lr: 0.005
> momentum: 0.9
> weight_decay: 0.0005
> lr_policy: "step"
> stepsize:500000
> gamma:0.457305051927326
> 
> display: 100
> max_iter: 4000000
> snapshot: 40000
> snapshot_prefix: "DeepFace_set003_net"
> 
> solver_mode: GPU
> 
> debug_info: false
