### ISSUE TITLE
pre-processing train data and val data

### ISSUE THREAD

**Issue by kingvision** [AlfredXiangWu/face_verification_experiment#7]
Hi:
  thank you for your sharing code.
  I know that pre-processing data for caffe train.
 But i do not know that how to pre-processing train data and val data using your code for face verification.
 can you give me some ideas?
 thnaks

**Comment by AlfredXiangWu** [comment]
1. Obtain 5 facial points of face image. You could use Yi Sun's work to extract landmark(http://mmlab.ie.cuhk.edu.hk/archive/CNN_FacePoint.htm).
2. Do face alignment via https://github.com/AlfredXiangWu/face_verification_experiment/blob/master/code/face_db_align.m
3. Generate lmdb.
