### ISSUE TITLE
关于测试结果的疑惑

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [AlfredXiangWu/face_verification_experiment#72]
吴老师，我用dlib进行关键点的检测 ，然后按您的数据矫正方法进行矫正，分别测试了A B C三个模型，但是在LFW上测试的准确率分别为 0.9677 0.9715 0.9777,均低于您的结果（约0.01），这正常吗？这是由于我们的关键点检测方法的差异造成的吗？谢谢。

**Comment by AlfredXiangWu** [comment]
应该是关键点的问题，我使用的是孙祎的算法http://mmlab.ie.cuhk.edu.hk/archive/CNN_FacePoint.htm
另外还对lfw关键点检测不准的一些图像进行了手工修正。

**Comment by rexnxiaobai** [comment]
可以用下mtcnn啊

**Comment by ZHAIXINGZHAIYUE** [comment]
@rexnxiaobai 您用mtcnn的方法测试过吗？结果如何？谢谢。

**Comment by ZHAIXINGZHAIYUE** [comment]
@AlfredXiangWu 谢谢您的解答，网上能多点像您这样负责又慷慨的人就好了。您方便透露一下您手工修正了多少数据吗？（以便我测试的时候心里有个底）。

**Comment by rexnxiaobai** [comment]
@ZHAIXINGZHAIYUE 具体测试数据 你可以去看他论文呀～ 我简单的试了一些图 效果很棒啊

**Comment by AlfredXiangWu** [comment]
这里有一份我切好的lfw的图片
链接: http://pan.baidu.com/s/1cvHLro 密码: c6di

另外我也测了下MTCNN，效果是很不错。

**Comment by ZHAIXINGZHAIYUE** [comment]
@AlfredXiangWu 万分感谢。

**Comment by tiankong1993** [comment]
@AlfredXiangWu 打扰一下,为啥lfw提取码是c6d阿,我也想对比一下您的效果

**Comment by AlfredXiangWu** [comment]
@tiankong1993 

链接:http://pan.baidu.com/s/1cvHLro 密码:c6di

**Comment by ZHAIXINGZHAIYUE** [comment]
@AlfredXiangWu 您好，我用您切好的lfw的图片测试了，和您论文的结果一点不差。我用的是最新版的caffe，用模型A B 来提取特征均无误。我也试了一下用mtcnn的方法，使用模型C, 100%-EER ：0.9803.。与您测得的结果是否相同？谢谢。

**Comment by rexnxiaobai** [comment]
@AlfredXiangWu @ZHAIXINGZHAIYUE 切好的lfw可以再给我份嘛，之前下的那份谜一样的不见了。。😂

**Comment by a00achild1** [comment]
@AlfredXiangWu @ZHAIXINGZHAIYUE 
The link of baidu is missed, so I download the database from another issue ([https://github.com/happynear/NormFace/issues/4](url)) which is provided by happynear, the link is at below:
[https://drive.google.com/file/d/0B0OhXbSTAU1HTU91T1I0bU5DV2c/view](url)
I'm not sure this one is exactly provided by @AlfredXiangWu 
But when I test with this lfw database with provided matlab code, I got different results.
LightenedCNN_C:
1. 100%-EER: 0.9820
2. TPR@FAR=1%: 0.9753
3. TPR@FAR=0.1%: 0.9587
4. TPR@FAR=0%: 0.9493

And I also tried with MTCNN, but got a little loss on the accuracy either.
Could I get the cropped lfw database from you to reproduce the same result?
Thanks a lot!
