### ISSUE TITLE
Did you clean up the MS-Celeb-1M data before training?

### ISSUE THREAD

**Issue by Martyn10** [AlfredXiangWu/face_verification_experiment#73]
Hi,
There are a lot of incorrectly labelled faces in this data set. Did you try to remove these before training or did you just use it as is?

Thanks

**Comment by AlfredXiangWu** [comment]
I use a simple bootstrapping method to automatically remove the noisy labeled face images. The new version paper will be published on arXiv soon. 

Besides, I will also publish the list after bootstrapping.

**Comment by Martyn10** [comment]
Fantastic, thanks for releasing your work to the public. It's really helpful :)
