### ISSUE TITLE
关于训练参数

### ISSUE THREAD

**Issue by jiangxuehan** [AlfredXiangWu/face_verification_experiment#74]
@AlfredXiangWu : 
    请问Model C训练时的batch_size以及lr_policy如何设置的? 还有MFM 3/2的 prototxt是否方便公布？

**Comment by AlfredXiangWu** [comment]
batch size 32或者64都可以，lr就按照论文里写方式去调整就好了
MFM 3/2的暂时不会公布，论文中有简单描述实现，可以自己按照描述配置。
