### ISSUE TITLE
How to do face recognition using this model

### ISSUE THREAD

**Issue by sudevbohra** [AlfredXiangWu/face_verification_experiment#76]
Is it correct that to compare two faces and see if they are the same we just extra 99891 feature vector from the two faces, and calculate cosine similarilty between these two feature vectors and that can be used as a similarity measure? 

What thresholding of cosine similarily would you recommend for saying two faces are from the same person?

**Comment by AlfredXiangWu** [comment]
You can use the ROC to evaluate the performance of the face verification task. In practice, according to the security of your face recognition system,  the score at EER, TPR@FAR=1%, TPR@FAR=0.1% etc. can be chosen as the threshold to measure whether two face images are the same person or not

**Comment by sudevbohra** [comment]
Thank you so much.

What are the scores at EER, TPR@FAR=1%, TPR@FAR=0.1%?

**Comment by AlfredXiangWu** [comment]
The definitions of these concepts are from ROC. You can find the details from the wiki (https://en.wikipedia.org/wiki/Receiver_operating_characteristic).
