### ISSUE TITLE
why the model C  is so big?

### ISSUE THREAD

**Issue by wuqiangch** [AlfredXiangWu/face_verification_experiment#78]
why the model C  is so big? 120M

**Comment by Martyn10** [comment]
The fc2 layer grows in size depending on how many identities are used for training. If you aren't training the model and want to use it for deployment you can remove this layer.
The below python code should work and reduced the model size to 21MB for me:
`
import caffe
net_new = caffe.Net('LightCNN_FC2_Removed.prototxt','LightenedCNN_C.caffemodel',caffe.TEST)
net_new.save('my_new_model.caffemodel')`


You will need to rename the below file to LightCNN_FC2_Removed.prototxt
[LightCNN_FC2_Removed.txt](https://github.com/AlfredXiangWu/face_verification_experiment/files/628814/LightCNN_FC2_Removed.txt)

**Comment by wuqiangch** [comment]
@Martyn10  Thanks very much!
