### ISSUE TITLE
the model c can not cat 

### ISSUE THREAD

**Issue by twinsyssy1018** [AlfredXiangWu/face_verification_experiment#80]
hi thank you for your sharing ,but i tried many times ,the two tar files can not be cat together ,is there something wrong?
i use this command:
cat tar.gz* | tar xj

**Comment by AlfredXiangWu** [comment]
You can use the command:
`cat LightenedCNN_C.tar.gz0* > LightenedCNN_C.tar.gz`
`tar -zxvf LightenedCNN_C.tar.gz`

**Comment by twinsyssy1018** [comment]
thank you. it works
