### ISSUE TITLE
how to extract features for gray-scale image

### ISSUE THREAD

**Issue by silinzhu** [AlfredXiangWu/face_verification_experiment#82]
hi, could you please tell me how to extract features for gray-scale image using caffe_ftr.py?
I've tried several times, but it doesn't work. Did it work for the old version of caffe? 
I 've found that the LFW features in the result file, and the dimension of one feature is 256. However, model A\B\C, none of them support 256 dims output. can you tell me how to do it?
Thank you very much!

**Comment by AlfredXiangWu** [comment]
The caffe_ftr.py is based on caffe-rc. If you use the caffe-rc3, you may modify some code. Certainly, it is not necessary to use caffe_ftr.py to extract features. You can also write the feature extraction code yourself to use deploy.prototxt and caffemodel by C++/Python/Matlab. 

The feature layer for A model is eltwise6 ant it is eltwise_fc1 for B and C model.

**Comment by silinzhu** [comment]
thanks
