### ISSUE TITLE
would you tell me where i can find lfw_pairs.mat

### ISSUE THREAD

**Issue by silinzhu** [AlfredXiangWu/face_verification_experiment#84]
hi, I want to evaluate the model by your matlab code. And your code "evaluation.m" includes this load('lfw_pairs.mat'), so i want to know the format of lfw_pairs.mat or where i can download it. Thank you very much!

**Comment by AlfredXiangWu** [comment]
https://github.com/AlfredXiangWu/face_verification_experiment/blob/master/code/lfw_pairs.mat

**Comment by silinzhu** [comment]
Thanks a lot!
