### ISSUE TITLE
About the LFW test？

### ISSUE THREAD

**Issue by shakevincent** [AlfredXiangWu/face_verification_experiment#86]
Hi Mr Wu
    it's amazing to see the great performance your network achieves.So I test the modelC.caffemodel on LFW,the accuracy is 98.88% , But the different people cos distance is only 0.01 or negative,I want to know the different people cos distance when you are testing ? thank you

**Comment by AlfredXiangWu** [comment]
The scores of different people is actually only 0.01 or even negative. Note that the cosine similarity is in a range from -1 to 1.

**Comment by shakevincent** [comment]
@AlfredXiangWu Thank you  I got it
