### ISSUE TITLE
the feaure extract problem

### ISSUE THREAD

**Issue by catcherliu** [AlfredXiangWu/face_verification_experiment#88]
hello,WuXiang:
    I have tried many times on my own test dataset using your LightenedCNN_C.caffemodle,but the result is very bad. and i think it must be my feature extract program is wrong.because your model is dong well on LFW.what troubles me most is i don't konw which step is wrong on my code.so,,,,,,would you please give the feature extracting program to me,my email is 958787279@qq.com,thanks a lot.

**Comment by AlfredXiangWu** [comment]
https://github.com/AlfredXiangWu/caffe/blob/caffe-rc3/tools/extract_features_to_file.cpp
There is a feature extraction code for caffe by C++. You can put it in './tool/' and make it.
But I don't recommend you to use it because the code is followed my own style.

**Comment by lmmcc** [comment]
thanks a lot,i will follow the c++ code,and check which step is wrong in my code........

**Comment by catcherliu** [comment]
thanks a lot,i will read the c++ code and check which step is wrong in my code......

**Comment by catcherliu** [comment]
hello.wu:
  i tried your extract_features_to_file program using the LightenedCNN_C_deploy.prototxt and it't model you have given out.....but i got the error 
![image](https://cloud.githubusercontent.com/assets/10055770/21414412/26ea9f8c-c83a-11e6-92ee-482aa748684e.png) likes this....meanwhile ,,,,i use the tool extract_features.bin it work out well...... what problem of this error?

**Comment by catcherliu** [comment]
ths a lot .i have solved this problem by other way,,,best wishes to u!
