### ISSUE TITLE
Feature extraction - shape error

### ISSUE THREAD

**Issue by naranjuelo** [AlfredXiangWu/face_verification_experiment#9]
Hi!

Thank you for sharing your approaches. 

When I use your python code for feature extraction, I get the error "ValueError: could not broadcast input array from shape (64,3,28,28) into shape (64,1,28,28)". I am a little confused about what should I change.

I'm using as inputs:
- your pretrained model (DeepFace_set003_net_iter.caffemodel) 
- your network definition (DeepFace_set003.prototxt) 
- an image list of some LFW grayscale images' path and labels

Thank you!!

**Comment by AlfredXiangWu** [comment]
"ValueError: could not broadcast input array from shape (64,**3**,28,28) into shape (64,**1**,28,28)". 
I think you could check your input image format whether it is gray-scale or not.

**Comment by naranjuelo** [comment]
Yes, I thought it was gray-scale, but after loading it I realized it had three channels, so I solved it getting just the channel I needed: 

img = caffe.io.load_image(path, color = not image_as_grey)
gi = img[:, :, 0]
img = np.reshape(gi, (250,250,1))

Then I have another problem, taking into account that the feature layer you extract is 'eltwise6' and that the layer's shape size is 2, there are some lines of the code that will crush:

features_shape = (len(image_list), shp[1], shp[2], shp[3]).
features = np.empty(features_shape, dtype='float32', order='C')
features[cnt-len(inputs)+1:cnt+1, :,:,:] = blobs[layer_name][0:len(inputs),:,:,:].copy()

Should I remove shp[2] and shp[3] ? So the code would be:

features_shape = (leng(inptu ims), shp[1])
features = np.empty(features_shape, dtype='float32', order='C')
features[cnt-len(inputs)+1:cnt+1, :] = blobs[layer_name][0:len(inputs),:].copy()

I thought this was the solution (the code also worked) but I'm not very sure if the results I'm getting are correct.

**Comment by AlfredXiangWu** [comment]
I think your solution is OK to extract features by my caffemodel, but could you make sure the layer's shape size is 2? Is there anything wrong?

As far as I know, for any layer of caffe, the size of input and output should be 4 which is batch_size, channel, width and height. For example, the shape of 'eltwise6' should be (batch_size, 256, 1, 1).

**Comment by naranjuelo** [comment]
Sorry for the delay. Yes, I've checked the layer's shape size and it seems to be 2 (batch_size, 256).

**Comment by AlfredXiangWu** [comment]
I have no idea about the difference. Maybe, the version of caffe leads to the result due to the different interface. I use the caffe-rc for training and testing CNN and what about you?

**Comment by naranjuelo** [comment]
Maybe... I'm using the following branch of Caffe for Windows: https://github.com/willyd/caffe.

**Comment by liyheart** [comment]
Hi, thank you for your shares. I also confronted the problem. I run the similar code to ensure the shape of  input image is (256, 256, 1) by img = skimage.color.rgb2gray(img)
        img = img[:, :, np.newaxis]
        print 'image shape: ', img.shape
however, another problem exposed:
File "/home/liy/caffe-hybrid_dev/python/caffe/pycaffe.py", line 307, in _Net_preprocess
    caffe_in = caffe_in[:, :, channel_order]
IndexError: index 2 is out of bounds for axis 2 with size 1

and The command is "python caffe_ftr.py ./proto/DeepFace_set003.prototxt ./model/DeepFace_set003_net_iter.caffemodel ./imgs/ labels eltwise6 ./tmp.mat
"
What's the problem with this?  All the code I used was downloaded from your github website, and run under ubuntu. Please help me, thanks!
