### ISSUE TITLE
求一份切好的lfw

### ISSUE THREAD

**Issue by rexnxiaobai** [AlfredXiangWu/face_verification_experiment#91]
亲 可以麻烦再给一下切好的lfw嘛～ 本来的链接失效了 我之前下载好的莫名消失了😂  非常感谢～

**Comment by AlfredXiangWu** [comment]
链接: http://pan.baidu.com/s/1jIOAfrw 密码: bcm5

**Comment by tinazliu** [comment]
您好,不好意思打擾了，最近拜讀吳老師的paper,所學良多，想實踐在keras上面。但都一直做不到預期的結果，想說可能training data沒有做好~
請問能在提供一次切好的CASIA嗎?萬分感謝!! @rexnxiaobai @AlfredXiangWu
