### ISSUE TITLE
which version of ms-celeb-1m do you use

### ISSUE THREAD

**Issue by westpilgrim** [AlfredXiangWu/face_verification_experiment#93]
hi , xiang wu:

which version of ms-celeb-1m do you use? full , cropped , or aligned ?

if you use the aligned version, I wonder if you train directly on it or after running your own alignment algorithm?cuz the aspect ration of the aligned version is different from your model.

**Comment by AlfredXiangWu** [comment]
The full or cropped MS-Celeb-1M is recommended for training.

**Comment by westpilgrim** [comment]
thank you
