### ISSUE TITLE
Dataset Size for Training set and Testing set of my own dataset

### ISSUE THREAD

**Issue by psakamoori** [AlfredXiangWu/face_verification_experiment#96]
Hi,

I see below table with size's picked for CASIA-WebFace training and lfw testing data set

Dataset	                     size	    ec_mc_y	ec_y
Training set (CASIA)   144x144	48	         48
Testing set (LFW)       128x128	48	        40

How to choose these sizes for my own dataset (Training and Testing)?
What should be size of "validation" samples during training?
Any help here...

**Comment by AlfredXiangWu** [comment]
The size of input for the light CNN is **128*128**. The 144*144 for training set aims to use "crop" data augmentation. The ec_mc_y and ec_y is the parameters of face alignment we used for training and testing. 

You can choose other alignment methods to normalize your face images.
