### ISSUE TITLE
Extract feature of images

### ISSUE THREAD

**Issue by steven-chow** [AlfredXiangWu/face_verification_experiment#97]
Hi, everyone!

I want to do feature extraction using the model, the question is in image preprocessing stage, whether i need to minus the mean, like:

cropImg = imread('xxx.jpg');     %  xxx.jpg is already aligned
cropImg  = (cropImg  - 127.5)/128;   
cropImg = permute(cropImg, [2,1,3]);
cropImg = cropImg(:,:,[3,2,1]);

Thank you!

**Comment by AlfredXiangWu** [comment]
I don't minus the mean when training. So when extracting features for images, you should only divide each pixel value by 255.

**Comment by steven-chow** [comment]
Thank you!
